// Myo Translation Keys
#define INPUT_QUATERNION_X "quatDataX"
#define INPUT_QUATERNION_Y "quatDataY"
#define INPUT_QUATERNION_Z "quatDataZ"
#define INPUT_QUATERNION_W "quatDataW"
#define INPUT_ARM "arm"
#define INPUT_X_DIRECTION "xDirection"

// Averaging Keys
#define QUAT_DATA_X "quatDataX"
#define QUAT_DATA_Y "quatDataY"
#define QUAT_DATA_Z "quatDataZ"
#define QUAT_DATA_W "quatDataW"
#define ACCEL_DATA_X "accelDataX"
#define ACCEL_DATA_Y "accelDataY"
#define ACCEL_DATA_Z "accelDataZ"
#define GYRO_DATA_X "gyroDataX"
#define GYRO_DATA_Y "gyroDataY"
#define GYRO_DATA_Z "gyroDataZ"
#define RSSI        "rssi"